### ISSUE TITLE
Trust for London files not loading in Insights

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/Insights#168]
via @KDuerden 

Both 'Grants 2018-2020' and 'Covid-19 Grants' files published by Trust for London don't load. The other does. The two that don't load are Google Sheets and the other file is Excel. 

This is the error message for Grants 2018-2020 When I download the files directly and tried to upload into 360Insights I got an error (maybe the same error?)

```
Traceback (most recent call last): 
File "/app/.heroku/python/lib/python3.8/site-packages/rq/worker.py", line 975, in perform_job rv = job.perform() 
File "/app/.heroku/python/lib/python3.8/site-packages/rq/job.py", line 692, in perform self._result = self._execute() 
File "/app/.heroku/python/lib/python3.8/site-packages/rq/job.py", line 698, in _execute return self.func(*self.args, **self.kwargs) 
File "/app/tsg_insights/data/process.py", line 138, in get_dataframe_from_url df = data_preparation.run() 
File "/app/tsg_insights/data/process.py", line 214, in run df = stage.run() 
File "/app/tsg_insights/data/process.py", line 253, in run self.df = ThreeSixtyGiving.from_url(url).to_pandas() 
File "/app/.heroku/python/lib/python3.8/site-packages/threesixty/threesixty.py", line 89, in from_url c = cls.from_
File(t, 
Filetype, **kwargs) 
File "/app/.heroku/python/lib/python3.8/site-packages/threesixty/threesixty.py", line 114, in from_
File return cls.from_excel(f, **kwargs) 
File "/app/.heroku/python/lib/python3.8/site-packages/threesixty/threesixty.py", line 181, in from_excel flattentool.unflatten( 
File "/app/.heroku/python/lib/python3.8/site-packages/flattentool/init.py", line 182, in unflatten spreadsheet_input.read_sheets() 
File "/app/.heroku/python/lib/python3.8/site-packages/flattentool/input.py", line 558, in read_sheets self.workbook = openpyxl.load_workbook(self.input_name, data_only=True) 
File "/app/.heroku/python/lib/python3.8/site-packages/openpyxl/reader/excel.py", line 317, in load_workbook reader.read() 
File "/app/.heroku/python/lib/python3.8/site-packages/openpyxl/reader/excel.py", line 282, in read self.read_worksheets() 
File "/app/.heroku/python/lib/python3.8/site-packages/openpyxl/reader/excel.py", line 228, in read_worksheets ws_parser.bind_all() 
File "/app/.heroku/python/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py", line 443, in bind_all self.bind_merged_cells() 
File "/app/.heroku/python/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py", line 380, in bind_merged_cells self.ws._clean_merge_range(mcr) 
File "/app/.heroku/python/lib/python3.8/site-packages/openpyxl/worksheet/worksheet.py", line 607, in _clean_merge_range mcr.format() 
File "/app/.heroku/python/lib/python3.8/site-packages/openpyxl/worksheet/merge.py", line 109, in format if side.style is None: AttributeError: 'NoneType' object has no attribute 'style'
```

@michaelwood 
I think recognise this as a bug in openpyxl that is now fixed and just requires an upgrade in Insights

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [openpyxl issue loading Trust for London data into Insights](https://trello.com/c/8MEKKTiK/207-openpyxl-issue-loading-trust-for-london-data-into-insights)

**Comment by michaelwood** [comment]
This is not reproducible using openpyxl 2.5.8. Which is the specified version in threesixty-parser however flattentool is now bringing the version  up to 3.0.6 which appears to have/cause this to be an exception.

Dependency chain is threesixty-parser -> flatten-tool -> openpyxl
