### ISSUE TITLE
Unicode decode error with grants CSV

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#32]
<https://www.coop.co.uk/downloads/causes-data-2017.csv> (large download)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/app/apps/file_load.py", line 143, in parse_contents
    df = get_dataframe(filename, contents, date)
  File "/app/apps/file_load.py", line 94, in get_dataframe
    io.StringIO(contents.decode('utf-8')))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 1273585: invalid start byte
```

**Comment by drkane** [comment]
Link to issue #27
